### ISSUE TITLE
手动构建的镜像运行错误

### ISSUE THREAD

**Issue by syouko** [crazygit/openwrt-x86-64#1]
采用以下版本openwrt
https://downloads.openwrt.org/releases/19.07.2/targets/x86/64/openwrt-19.07.2-x86-64-combined-squashfs.img.gz

将openwrt的下载后的.img.gz文件解压后得到.img文件作为构建镜像的文件基础

根据作者的build.sh内的命令手动构建的镜像

docker build -f Dockerfile文件 . -t abc/edf:v1

Dockerfile只去掉了对应的ARG FIRMWARE，
将下面的手动更改为 ADD img文件

如此创建后得到的镜像
docker run abc/def:v1
之后报错

docker: Error response from daemon: unable to find user root: no matching enteries in passwd file
ERRO[0000] error waiting for container: context canceled

请问是我使用docker的环境中root用户的问题吗？

**Comment by crazygit** [comment]
> 采用以下版本openwrt
> https://downloads.openwrt.org/releases/19.07.2/targets/x86/64/openwrt-19.07.2-x86-64-combined-squashfs.img.gz
> 
> 将openwrt的下载后的.img.gz文件解压后得到.img文件作为构建镜像的文件基础
> 
> 根据作者的build.sh内的命令手动构建的镜像
> 
> docker build -f Dockerfile文件 . -t abc/edf:v1
> 
> Dockerfile只去掉了对应的ARG FIRMWARE，
> 将下面的手动更改为 ADD img文件
> 
> 如此创建后得到的镜像
> docker run abc/def:v1
> 之后报错
> 
> docker: Error response from daemon: unable to find user root: no matching enteries in passwd file
> ERRO[0000] error waiting for container: context canceled
> 
> 请问是我使用docker的环境中root用户的问题吗？

看起来是你选择使用的镜像里面没有root用户引起的。使用文件名为`generic-rootfs.tar.gz`镜像试试

**Comment by syouko** [comment]
> > 采用以下版本的openwrt 
> > https://downloads.openwrt.org/releases/19.07.2/targets/x86/64/openwrt-19.07.2-x86-64-combined-squashfs.img.gz
> > 将openwrt的下载后的.img.gz文件解压后得到.img文件作为内置的文件基础
> > 根据作者的build.sh内的命令手动合并的合并
> > docker build -f Dockerfile文件 -t abc / edf：v1
> > Dockerfile只去掉了对应的ARG FIRMWARE，
> > 将下面的手动更改为ADD img文件
> > 如此创建后得到的常设docker 
> > run abc / def：v1 
> > 之后报错
> > 泊坞窗：来自守护程序的错误响应：无法找到用户根目录：passwd文件
> > ERRO [0000]中没有匹配的输入项，等待容器时出错：上下文已取消
> > 请问是我使用docker的环境中root用户的问题吗？
> 
> 看起来是你选择使用的镜像里面没有根用户引起的。文件使用名为`generic-rootfs.tar.gz`它的镜像就是试试

确实只有这一个镜像可以。。。
