### ISSUE TITLE
关于宿主机不能连接openwrt

### ISSUE THREAD

**Issue by a-little-cat** [crazygit/openwrt-x86-64#3]
您好,我的部署环境和您的非常接近,我是在寻找一个全插件镜像时搜到的您的仓库..

宿主机不能连接openwrt是docker的限制,官方文档中提到,由于安全限制,macvlan的container不能和host进行communicate.

不过我最终搜到了解决方案:创建一个新的虚拟网卡,做中转.
[参考链接](https://bianchengboke.com/2019/08/%E5%9C%A8docker%E4%B8%AD%E8%BF%90%E8%A1%8Copenwrt/)

这个结局方案是基于ifupdown(ubuntu20的默认网络管理工具升级为netplan),所以在我的环境,还需要修改ubuntu20的网络管理工具为ifupdown.

[参考链接](https://askubuntu.com/questions/1031709/ubuntu-18-04-switch-back-to-etc-network-interfaces)

希望能给您提供帮助

**Comment by matthuo333** [comment]
你有用arm 平台的docker op 么？  我的为什么run后，防火墙貌似失效，自定义防火墙也不生效

**Comment by a-little-cat** [comment]
我的环境是x86,没有在arm上使用过.
我的环境是硬路由padavan加软路由openwrt,防火墙功能放在了padavan.
